---
openapi: 3.0.0
info:
  title: Send API
  description: API to send emails
  contact:
    email: joaopedrodslv@gmail.com
  version: 1.0.0
servers:
- url: /api/v1
paths:
  /mail:
    post:
      summary: Send email
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_request'
        required: true
      responses:
        "201":
          description: Email sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
components:
  schemas:
    body_response:
      type: object
      properties:
        from:
          type: string
          format: email
          example: no-reply@server.com
        to:
          type: string
          format: email
          example: jondoe@foo.com
        cc:
          type: array
          items:
            type: string 
            format: email
          example: [jondoe@foo.com]
        format:
          type: string
          example: markdown
          enum:
          - mardown
          - text
          - html
        subject:
          type: string
          example: Subject of the email
        body:
          type: string
          example: Body text
    body_request:
      required:
      - body
      - from
      - subject
      - to
      type: object
      properties:
        from:
          type: string
          format: email
          example: no-reply@server.com
        to:
          type: string
          format: email
          example: jondoe@foo.com
        cc:
          type: array
          items:
            type: string 
            format: email
          example: [jondoe@foo.com]
        format:
          type: string
          example: markdown
          enum:
          - mardown
          - text
          - html
        subject:
          type: string
          example: Subject of the email
        body:
          type: string
          example: Body text
